### PR TITLE
Require JSON, removed code not compatible with JSON input files

### PR DESCRIPTION
**Pull request by MattRolchigo**

### CODE REVIEW

**Review by streeve — COMMENTED** [review]
There are some FIXME notes in the analysis about improvements once JSON is required - I assume you want to do that in a separate PR

**Comment by MattRolchigo** [comment]
Yeah, there's a bunch of moving things/rewriting that I'm planning on doing in the analysis routine, essentially putting more things into the class to clean up the function inputs. But since this PR is basically just deleting old code, I felt like also adding a bunch of code would be better to do separateyl

**Comment by streeve** [comment]
Sounds good - just that one very minor change then

**Review by streeve — APPROVED** [review]
Easy review :)

**Pull request merged**
