### PR TITLE
Update Readme

### PR DESCRIPTION
**Pull request by streeve**
- [x] Links for dependencies
- [x] Up to date min version requirements
- [x] Description of building/running tests
- [x] Remove deprecated inputs
~Update any new/changed inputs or run behavior~

### CODE REVIEW

**Comment by streeve** [comment]
@MattRolchigo review or updates here?

**Comment by MattRolchigo** [comment]
I wasn't sure if you were waiting for all 5 boxes to be checked before reviewing/merging this... I know the json PR is going to affect the 5th box. Were there other deprecated inputs you wanted to get rid of in addition to those in #149 ?

**Comment by streeve** [comment]
> I wasn't sure if you were waiting for all 5 boxes to be checked before reviewing/merging this...

To be fair, I never actually said that I assumed you would be better suited to add the last two bullets, but that is what I intended. I would update it now, then add any json related changes to that PR

**Comment by MattRolchigo** [comment]
I removed the reference in the README to DecompositionStrategy, which is now deprecated. Otherwise I think the README files are up to date (until we add the json option, then we'll need to add a section)

**Comment by streeve** [comment]
Looks good - up to you to approve and merge

**Comment by MattRolchigo** [comment]
I added one more update, I can approve and merge this when you are ready

**Comment by streeve** [comment]
Looks good

**Comment by MattRolchigo** [comment]
Should we combine these commits?

**Review by MattRolchigo — APPROVED** [review]

**Pull request merged**
