### PR TITLE
Add core library header file

### PR DESCRIPTION
**Pull request by streeve**
Use in grain analysis

### CODE REVIEW

**Comment by MattRolchigo** [comment]
So this is just to simplify the include statements, so only one header file for ExaCA subroutines needs to be included in each of the analysis/src/*.hpp files?

**Comment by streeve** [comment]
> So this is just to simplify the include statements, so only one header file for ExaCA subroutines needs to be included in each of the analysis/src/*.hpp files?

Yeah, this will simplify another app using ExaCA as a library and the analysis is just our only example so far

**Comment by MattRolchigo** [comment]
Sounds good to me

**Comment by streeve** [comment]
> Sounds good to me

Cool, but do you "approve" of the changes?

**Comment by MattRolchigo** [comment]
I think I have to be requested as a reviewer first

**Review by MattRolchigo — APPROVED** [review]

**Pull request merged**
